Simplified interface for computing I(q,dq)
SasView/sasmodels pull request #563
Opened 2023-03-30 21:37 UTC by pkienzle

The PR provides a calculator for computing Iq, Iqxy and sesans Gxi.

To include support for single-point calculations a number of other pieces of code needed to change, including the resolution calculators and the SESANS calculator. These are on the SasView code path so need to be checked carefully.

The sasmodels internal data shim was modified to allow initialization with lists rather than numpy arrays. This does not affect SasView calculations.

The warning for invalid arcsin in SESANS was removed, and the mask updated to handle NaN values. This may affect the results of some SESANS calculations since the previous code did not exclude unreachable q values.

While debugging I noticed that the call to the calculator ignored misnamed model parameters. I modified the call to check that all parameters are used. This broke the hardsphere model tests since `radius_effective` is not a polydisperse parameter (PR#562). The tests will fail until that PR is pulled into master.

The call checks will not affect sasview, which goes through the SasviewModel code path to call the calculation kernel, but those using sasmodels directly with bumps may see errors popping up in their models if they have misnamed parameters.

2023-04-05 20:45 UTC, butlerpd commented
need somebody with sesans interest/knowledge to take a look - note the detailed writeup referenced in #564 ... @rmdalgliesh?

2023-05-08 19:46 UTC, caitwolf requested changes

2023-05-08 19:46 UTC, caitwolf commented on sasmodels/direct_model.py
> +    test_simple_interface()
Should this be switched back to the main function?

2023-05-12 15:15 UTC, caitwolf requested changes

2023-05-12 15:15 UTC, caitwolf commented on sasmodels/direct_model.py
> +                    q_width=data.dxw[index])
```suggestion
                res = resolution.Slit1D(
                    data.x[index],
                    q_length=data.dxl if data.dxl is None else data.dxl[index],
                    q_width=data.dxw if data.dxw is None else data.dxw[index]
                )
```

2023-05-12 15:15 UTC, caitwolf commented on sasmodels/direct_model.py
> +    data.dxl, data.dxw = _as_numpy(ql), _as_numpy(qw)
```suggestion
    data.dxl = _as_numpy([ql]*len(q) if np.isscalar(ql) else ql)
    data.dxw = _as_numpy([qw]*len(q) if np.isscalar(qw) else qw)
```

2023-05-12 15:15 UTC, caitwolf commented on sasmodels/direct_model.py
>                    and getattr(data, 'dxw', None) is not None):
```suggestion
                  or getattr(data, 'dxw', None) is not None):
```

2023-05-12 15:15 UTC, caitwolf commented on sasmodels/direct_model.py
> +    for slit geometry. Use 0 or None for infinite slits.
When I tested the Iq function with an infinite slit I ran into a couple errors. When qw=None, ql is still ignored and slit resolution is not applied. When using 0 I get an error due to the indexing on line 262-263. I made code suggestions in a few places that I think will fix this but need review. I made the assumption that the dxl and dxw attributes of Data1D should be kept as either None or an array of same length as q.

2023-06-27 15:33 UTC, caitwolf approved these changes
I tested the infinite slit cases and the code worked as expected. It no longer ignored the slit resolution if only one of the length and width was provided.

2023-06-27 15:35 UTC, merged